<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9FxPh29\Lemric_Sail_Tests_Fixtures_TestKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9FxPh29/Lemric_Sail_Tests_Fixtures_TestKernelTestDebugContainer.php') {
    touch(__DIR__.'/Container9FxPh29.legacy');

    return;
}

if (!\class_exists(Lemric_Sail_Tests_Fixtures_TestKernelTestDebugContainer::class, false)) {
    \class_alias(\Container9FxPh29\Lemric_Sail_Tests_Fixtures_TestKernelTestDebugContainer::class, Lemric_Sail_Tests_Fixtures_TestKernelTestDebugContainer::class, false);
}

return new \Container9FxPh29\Lemric_Sail_Tests_Fixtures_TestKernelTestDebugContainer([
    'container.build_hash' => '9FxPh29',
    'container.build_id' => '36b844ef',
    'container.build_time' => 1723895872,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container9FxPh29');
