<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRmieRr7\Lemric_Sail_Tests_Fixtures_TestKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRmieRr7/Lemric_Sail_Tests_Fixtures_TestKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerRmieRr7.legacy');

    return;
}

if (!\class_exists(Lemric_Sail_Tests_Fixtures_TestKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerRmieRr7\Lemric_Sail_Tests_Fixtures_TestKernelTestDebugContainer::class, Lemric_Sail_Tests_Fixtures_TestKernelTestDebugContainer::class, false);
}

return new \ContainerRmieRr7\Lemric_Sail_Tests_Fixtures_TestKernelTestDebugContainer([
    'container.build_hash' => 'RmieRr7',
    'container.build_id' => '30582e8c',
    'container.build_time' => 1723897574,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRmieRr7');
